/*
 * RESP.app Extension server
 * RESP.app Extension Server API allows you to extend RESP.app with your custom data formatters
 *
 * The version of the OpenAPI document: 2022.0-preview1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.javalover123.resp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * EncodePayload
 */
@JsonPropertyOrder({
  EncodePayload.JSON_PROPERTY_DATA,
  EncodePayload.JSON_PROPERTY_METADATA
})
@JsonTypeName("EncodePayload")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", date="2022-07-30T22:32:13.307768900+08:00[Asia/Shanghai]")
@Introspected
public class EncodePayload {
    public static final String JSON_PROPERTY_DATA = "data";
    private String data;

    public static final String JSON_PROPERTY_METADATA = "metadata";
    private Object metadata;

    public EncodePayload() {
    }

    public EncodePayload data(String data) {
        this.data = data;
        return this;
    }

    /**
     * Base64 encoded string
     * @return data
     **/
    @Nullable
    @Schema(name = "data", description = "Base64 encoded string", required = false)
    @JsonProperty(JSON_PROPERTY_DATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getData() {
        return data;
    }

    @JsonProperty(JSON_PROPERTY_DATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setData(String data) {
        this.data = data;
    }

    public EncodePayload metadata(Object metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Metadata from formatter custom ui forms
     * @return metadata
     **/
    @Nullable
    @Schema(name = "metadata", description = "Metadata from formatter custom ui forms", required = false)
    @JsonProperty(JSON_PROPERTY_METADATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Object getMetadata() {
        return metadata;
    }

    @JsonProperty(JSON_PROPERTY_METADATA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetadata(Object metadata) {
        this.metadata = metadata;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EncodePayload encodePayload = (EncodePayload) o;
        return Objects.equals(this.data, encodePayload.data) &&
            Objects.equals(this.metadata, encodePayload.metadata);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, metadata);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EncodePayload {\n");
        sb.append("    data: ").append(toIndentedString(data)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
